// This file is auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Run that command after setting up your Supabase project to get full type safety.
// For now, using 'any' as a placeholder.
export type Database = any
